use_frameworks!

def common_pods
    pod 'SwiftLint', '0.24.0'
end

def dependent_pods
    # example - pod 'podname', :git => 'path', :branch => 'development'
end

def example_project
    # pod 'PROJECT', :path => './'
end

workspace 'PROJECT'
target 'PROJECT' do
    project 'PROJECT.xcodeproj'
    common_pods
    dependent_pods
    example_project
    target 'PROJECTTests' do
        inherit! :search_paths
    end
end

target 'PROJECTExample' do
    project 'Example/PROJECTExample.xcodeproj'
    common_pods
    dependent_pods
    example_project
end
